# Generated by Django 3.1.6 on 2021-03-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210311_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(db_table='article_tags', related_name='articles_new', to='article.Tag'),
        ),
    ]
