# Generated by Django 3.1.6 on 2021-03-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_transactions_tags_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags_old',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
