# Generated by Django 3.1.6 on 2021-03-15 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210311_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок'),
        ),
    ]
