# Generated by Django 3.1.6 on 2021-04-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_remove_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
